### ISSUE TITLE
Aquera Heat pump: could not authenticate to Aquarea Smart Panasonic

### ISSUE THREAD

**Issue by Aldou63** [sdamasoc/domoticz_panasonic_CZ-TACG1#15]
hi
I have just install a panasonic aquaera heat pump air-water (WH-SXC09H3E5). I am testing plugin for my domoticz supervisor. But plugin could not authenticate to Aquarea Smart Panasonic.
Other question: what is the meaning of ->Log: Aquarea devices (deviceType=2) _**IS IN ALPHA MODE**_  ?

Connection to accsmart_url is OK and data inside device list are correct:

2024-04-29 16:28:52.844 Panasonic: get_devices={"a2wStatus":{"statusCode":200},"uiFlg":false,"groupCount":1,"groupList":[{"groupId":1326917,"groupName":"My House","pairingList":[],"deviceList":[{"deviceGuid":"B664968599","deviceType":"2","deviceName":"PAC","connectionStatus":0,"operationMode":1,"zoneStatus":[{"zoneId":1,"operationStatus":0,"temperature":-5},{"zoneId":2}],"tankStatus":{}}]}]}

But connection to https://aquarea-smart.panasonic.com don't work:

2024-04-29 16:28:51.637 Panasonic: Could not authenticate to Aquarea Smart Panasonic: {"errorCode":4194305,"message":[{"errorMessage":"Logged out due to system error. Please login again after a while.","errorCode":"1000-0999","additionalErrorCode":null}],"accessToken":{}}

Domoticz log:
2024-04-29 16:28:48.369 Panasonic: Worker thread started.
2024-04-29 16:28:48.851 Panasonic: Getting latest Comfort Cloud version from the App Store...
2024-04-29 16:28:48.369 Status: Panasonic: Entering work loop.
2024-04-29 16:28:48.369 Status: Panasonic: Started.
2024-04-29 16:28:48.849 Status: Panasonic: Initialized version 2.0.0, author 'sdamasoc'
2024-04-29 16:28:49.504 Panasonic: get_app_version=1.20.1
2024-04-29 16:28:51.426 Panasonic: get_token={"uToken":"cc8f63b0063411ef98e3e90447819eb6","country":"FR","extUsrId":"3c620590000811efa1734da4377389e6","clientId":"cc955720063411ef98e4e90447818eb6","language":0}
2024-04-29 16:28:51.637 Panasonic: Could not authenticate to Aquarea Smart Panasonic: {"errorCode":4194305,"message":[{"errorMessage":"Logged out due to system error. Please login again after a while.","errorCode":"1000-0999","additionalErrorCode":null}],"accessToken":{}}
2024-04-29 16:28:52.844 Panasonic: get_devices={"a2wStatus":{"statusCode":200},"uiFlg":false,"groupCount":1,"groupList":[{"groupId":1326917,"groupName":"My House","pairingList":[],"deviceList":[{"deviceGuid":"B664968599","deviceType":"2","deviceName":"PAC","connectionStatus":0,"operationMode":1,"zoneStatus":[{"zoneId":1,"operationStatus":0,"temperature":-5},{"zoneId":2}],"tankStatus":{}}]}]}
2024-04-29 16:28:52.844 Panasonic: ##################################################################################
2024-04-29 16:28:52.844 Panasonic: ##################################################################################
2024-04-29 16:28:52.844 Panasonic: Aquarea devices (deviceType=2) IS IN ALPHA MODE
2024-04-29 16:28:53.015 Panasonic: Could not authenticate to Aquarea Smart Panasonic: {"errorCode":4194305,"message":[{"errorMessage":"Logged out due to system error. Please login again after a while.","errorCode":"1000-0999","additionalErrorCode":null}],"accessToken":{}}
2024-04-29 16:28:53.189 Panasonic: Token is expired, get a new token
2024-04-29 16:28:53.356 Panasonic: Could not authenticate to Aquarea Smart Panasonic: {"errorCode":4194305,"message":[{"errorMessage":"Logged out due to system error. Please login again after a while.","errorCode":"1000-0999","additionalErrorCode":null}],"accessToken":{}}
2024-04-29 16:28:53.541 Error: Panasonic: Retries exausted
2024-04-29 16:28:53.543 Error: Panasonic: Call to function 'onStart' failed, exception details:
2024-04-29 16:28:53.549 Error: Panasonic: Traceback (most recent call last):
2024-04-29 16:28:53.549 Error: Panasonic: File "/home/pi/domoticz/plugins/domoticz_panasonic_CZ-TACG1/plugin.py", line 203, in onStart
2024-04-29 16:28:53.549 Error: Panasonic: _plugin.onStart()
2024-04-29 16:28:53.549 Error: Panasonic: File "/home/pi/domoticz/plugins/domoticz_panasonic_CZ-TACG1/plugin.py", line 113, in onStart
2024-04-29 16:28:53.549 Error: Panasonic: aquarea.add_device(devicename, nbdevices)
2024-04-29 16:28:53.549 Error: Panasonic: File "/home/pi/domoticz/plugins/domoticz_panasonic_CZ-TACG1/aquarea.py", line 225, in add_device
2024-04-29 16:28:53.549 Error: Panasonic: device=load_device()
2024-04-29 16:28:53.549 Error: Panasonic: File "/home/pi/domoticz/plugins/domoticz_panasonic_CZ-TACG1/aquarea.py", line 71, in load_device
2024-04-29 16:28:53.549 Error: Panasonic: return load_device(True)
2024-04-29 16:28:53.549 Error: Panasonic: File "/home/pi/domoticz/plugins/domoticz_panasonic_CZ-TACG1/aquarea.py", line 75, in load_device
2024-04-29 16:28:53.549 Error: Panasonic: "deviceConf": json.loads(extract_from_regex(response.text, r"var deviceConf = eval\('\((.*)\)'\);"))
2024-04-29 16:28:53.549 Error: Panasonic: File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
2024-04-29 16:28:53.549 Error: Panasonic: raise TypeError(f'the JSON object must be str, bytes or bytearray, '
2024-04-29 16:28:53.549 Error: Panasonic: TypeError: the JSON object must be str, bytes or bytearray, not NoneType

Thanks for your help.

**Comment by sdamasoc** [comment]
Hi Aldou63,
Sorry for the late response. 
Aquarea devices are in alpha mode because I don’t have such devices. I’ve done the integration with the support of one of the users which shared his Panasonic account with me. 
There are 2 possibilities:
- Panasonic has changed the login protocol for aquarea
- you have a different type 2 device 

If you create an account for me I can try to debug and see what os happening. of course I will not change any setting without your permission.

**Comment by Aldou63** [comment]
Hi,
Thanks for your answer.
 I have created an account for you and send it by replying to the email I received in my mail box. 
Do you received it ? If not please explain me how I can send this information to you !

**Comment by sdamasoc** [comment]
No I did not receive it, my email is xxxx
Edit: got it now!

**Comment by sdamasoc** [comment]
Panasonic has completely changed the authentication procedure.
I made some changes, can you pull and test it?

Thanks for your help to maintain the plugin with the user to your aquarea device!

**Comment by Aldou63** [comment]
Now authentication is OK. Everything works well with Domoticz.
Thanks to Sergio !

**Comment by thron-1** [comment]
Hey Sergio, did not use the Domoticz plugin. Now I get the error 4106 
<img width="922" alt="Panasonic Error" src="https://github.com/sdamasoc/domoticz_panasonic_CZ-TACG1/assets/104089614/7f8f3c1b-f974-40c4-b546-6a03df4d3807">
Made a new puldown from Github but now change. My API Version is 1.18.0. 

Any suggestions?

Best Regards
Ingo
