### ISSUE TITLE
Problem with onHeartBeat

### ISSUE THREAD

**Issue by wimmme** [sdamasoc/domoticz_panasonic_CZ-TACG1#9]
Just installed this today, seems to do it's job, great, thanks !
Just receiving this error:

`2023-07-18 23:29:47.274 Error: Airco: Call to function 'onHeartbeat' failed, exception details:
2023-07-18 23:29:47.274 Error: Airco: Traceback (most recent call last):
2023-07-18 23:29:47.274 Error: Airco: File "/opt/domoticz/userdata/plugins/domoticz_panasonic_CZ-TACG1/plugin.py", line 297, in onHeartbeat
2023-07-18 23:29:47.274 Error: Airco: _plugin.onHeartbeat()
2023-07-18 23:29:47.274 Error: Airco: File "/opt/domoticz/userdata/plugins/domoticz_panasonic_CZ-TACG1/plugin.py", line 244, in onHeartbeat
2023-07-18 23:29:47.274 Error: Airco: if (Devices[x].sValue != value):
2023-07-18 23:29:47.274 Error: Airco: UnboundLocalError: local variable 'value' referenced before assignment`

**Comment by wimmme** [comment]
Seem to have found a working solution myself for this, although not the best (not a dev); created a pull request

**Comment by sdamasoc** [comment]
Hello, sorry for the delay but your correction seems ok for me, I've merge it.

Thanks for the contribution!
